Update License to be recognised by Github
DataDog/dd-sdk-android-gradle-plugin pull request #50
Opened 2021-09-27 08:53 UTC by xgouchet

### What does this PR do?

For now the License is not recognised by Github License detection

2021-09-27 09:13 UTC, 0xnm requested changes
PR contains redundant commit

2021-09-27 12:50 UTC, mariusc83 requested changes

2021-09-27 12:50 UTC, mariusc83 commented on dd-sdk-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt
> +            LOGGER.warn("Minifying disabled for variant ${variant.name}, no upload task created")
These were already on master, maybe you should try a rebase.

2021-09-29 06:02 UTC, mariusc83 approved these changes

2021-09-29 07:14 UTC, 0xnm approved these changes

2021-09-30 07:54 UTC, merged